version: '3'
services:
  postgresql:
    image: postgres:9.5
    container_name: postgres-it
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "effectless"